#! /bin/bash

cd `dirname $0`

arch=`uname -m`
tag=
platform=

if test "$arch" = "arm64" -o "$arch" = "aarch64"; then
    platform=linux/arm64
    tag=fullstack:arm64
else
    platform=linux/amd64
    tag=fullstack:latest
fi
docker ps -a -q --filter "name=fullstack-persistent" | xargs -r docker rm
docker images | grep "fullstack" | awk '{print $1":"$2}' | xargs -r docker rmi

dockerfile=Dockerfile
if test "$platform" = "linux/arm64"; then
    dockerfile=Dockerfile.arm64
fi

exec docker build -t "$tag" -f "$dockerfile" --platform "$platform" .